### ISSUE TITLE
Divide  data-modeling-tool repository into several repositories

### ISSUE THREAD

**Issue by eoaksnes** [equinor/data-modelling-tool#1417]
## Context ##

We want to split up the data-modeling-tool repository into several repositories.

## Issues ##

- [x] equinor/data-modelling-tool#1412 
- [x] equinor/data-modelling-tool#1427 
- [x] equinor/data-modelling-tool#1416 
- [x] equinor/data-modelling-tool#1415 
- [x] equinor/dm-app-analysis-platform#4  
- [x] equinor/data-modelling-tool#1413   
- [x] equinor/data-modelling-tool#1423 
- [x] equinor/data-modelling-tool#1410 
- [x] equinor/data-modelling-tool#1353 
- [x] equinor/data-modelling-tool#1409
- [x] equinor/data-modelling-tool#1423 
- [x] https://github.com/equinor/dm-cli/issues/4
- [x] https://github.com/equinor/dm-core-packages/issues/2
- [x] equinor/data-modelling-tool#1411 
- [x] https://github.com/equinor/data-modelling-storage-service/issues/260
- [x] https://github.com/equinor/dm-docs/issues/1
- [x] https://github.com/equinor/dm-core-packages/issues/5
- [x] equinor/data-modelling-tool#1428 
- [x] https://github.com/equinor/create-dm-app/issues/3
- [x] https://github.com/equinor/create-dm-app/issues/6
- [x] https://github.com/equinor/create-dm-app/issues/5
- [x] https://github.com/equinor/dm-cli/issues/7
- [x] https://github.com/equinor/dm-job/issues/3
- [x] equinor/data-modelling-tool#1364 
- [ ] write typedocs for dm-core
