### ISSUE TITLE
clean architecture transition

### ISSUE THREAD

**Issue by eoaksnes** [equinor/data-modelling-tool#179]
# Transition Plan

### General 
 - [x] Fix url to use /api/v2 (@sindre-nistad, #189)
 - [x] Rename `package` domain model to `sub_package` (@eoaksnes 75ade30ba78be5edd9e375a29b47f3a4e0a01549)
 - [x] Tree - Create renderIcon function #181 
 - [x] Remove tree specific attributes from index response (something like picture below)
Keep: id, children, nodeType (datasource | root-package | subpackage | file | entity-file etc)
![image](https://user-images.githubusercontent.com/1190419/65312997-e3cc4000-db93-11e9-9086-8d224148befe.png) (@eoaksnes #183)
 - [x] Created interfaces for repositories (abstract base classes) (@eoaksnes 75ade30ba78be5edd9e375a29b47f3a4e0a01549)
 - [x] Created dedicated MongoDbClient with basic add, update, get, delete and find functions (@eoaksnes 75ade30ba78be5edd9e375a29b47f3a4e0a01549)
  - [x] Replace `filename` with `title` for index (@eoaksnes)
  - [ ] Support personal workspace (@sindre-nistad)
        1) Get userid from oauth token stored in local storage
        2) Create data source from the user the first logs in to dmt database with `collection-<username>`

### Blueprint Page

 - [ ] Add data source (@soofstad)
 - [x] Get data source (@soofstad #194)

 -  [ ] Move dmt template get

- DataSourceNode
  - [x] DataSource -> New -> RootPackage (@eoaksnes #182)
  
- Root Package 
  -  [x] RootPackage -> Rename (@eoaksnes #193)
  -  [x] RootPackage -> Remove (@eoaksnes #192)

- FolderNode
  - [x] SubPackage - New -> Blueprint (@eoaksnes @cbuv @sindre-nistad @soofstad)
  - [x] SubPackage - New -> SubPackage (@eoaksnes #180)
  - [x] SubPackage - Rename (@eoaksnes)
  - [x] Remove sub package (@eoaksnes #187)

- Blueprint
  - [x] Remove (@eoaksnes #186)
  - [x] Rename (@eoaksnes)
  

### Entity Page

  - [x] Replace postEntityFile with addEntityFile that uses v2 api (@eoaksnes)

  - [ ] Support nested entity (@cbuv  #184)
  - [ ] Support array of nestes entities

### Other ideas 
   - [ ] Avoid storing both _id and id in documents
 
  - [ ] Avoid sending templateRef when creating RootPackage, SubPackage...?

  - [ ] templateRef split 

  - [ ] Only specify filename in files and subpackage lists. Same for version in root-package. 

```
"template": {
      "dataSource": "local-blueprints-equinor",
      "rootPackage": "blueprints/boxes",
      "version": "1.1.1",
      "filename": "ordinary"
    }
```
![image](https://user-images.githubusercontent.com/1190419/65411786-12ddee00-ddee-11e9-905f-c5c5de23ccdc.png)
