### ISSUE TITLE
Ui issues from 0.4 milestone

### ISSUE THREAD

**Issue by cbuv** [equinor/data-modelling-tool#425]
0.4 bugs
#### Mayor
- [x] add type in entities page from context menu array (add a wheel) ed32dfd166a97975793526d9f938b37d65a19f21
- [x] add type in blueprint page from context menu, create recipes #430
- [x] remove menu item on nested nodes is missing. (both blueprint and entities page) #432 

#### Minor:
From #432
only add remove on arrays or if single type is optional, moved to #435
