### ISSUE TITLE
stable release issues

### ISSUE THREAD

**Issue by cbuv** [equinor/data-modelling-tool#547]
### Refresh needed
Context menu issues
- [x] entities: add item: Todo -> list -> items -> create items  (api OK, refresh needed) fixed by #570
- [x] Rename (#559): TodoDemo -> Todo  <--- web crash, refresh works. fixed by #570
- [x] create root package (must refresh page) fixed by #570

### Minor:

- [x] use index recipe in edit form
- [x] dont allow remove array node and required single nodes from context menu #569
- [x] Delete: TodoDemo -> TodoList -> items <--- delete Error displayed in ui #569 36c88024183098ab2c492c50cfe154f5cc0e0288
- [x] Create Entity (#558): TodoDemo <---- create entity Todo  Error displayed in ui
 (ValueError: The meta data and tha 'data' object in the DTO does not match!)
- [x] recursive entities using array works (ParkingLot)
- [x] blueprints: create new root-package -> new blueprint -> add attribute -> create entity (message: "AttributeError: 'DTO' object has no attribute '_name'") #570
